#!/usr/bin/env python3
"""
Sanitize Python files by removing development process comments.
Keeps intent comments (docstrings, complexity warnings, API explanations).
"""
import re
import os
from pathlib import Path

# Patterns to remove
REMOVE_PATTERNS = [
    r'#\s*Phase\s+\d+[:\s].*$',  # Phase X comments
    r'#\s*Part of Phase\s+\d+.*$',  # Part of Phase X
    r'#\s*Satisfies Req\s+[\d.]+.*$',  # Satisfies Req X.Y
    r'#\s*AI generated.*$',  
    r'#\s*Generated by.*$',  
]

# Patterns to keep (don't remove these)
KEEP_PATTERNS = [
    r'^\s*"""',  # Docstrings
    r"^\s*'''",  # Docstrings
    r'#\s*O\(',  # Complexity notation
    r'#\s*type:',  # Type hints
    r'#\s*noqa',  # Linting directives
    r'#\s*pragma',  # Coverage directives
    r'#\s*pylint',  # Pylint directives
    r'#\s*mypy',  # Mypy directives
]

def should_keep_line(line: str) -> bool:
    """Check if line should be kept based on patterns."""
    # Always keep docstrings and special directives
    for pattern in KEEP_PATTERNS:
        if re.search(pattern, line):
            return True
    return False

def sanitize_line(line: str) -> str:
    """Remove process comments from a line."""
    if should_keep_line(line):
        return line
    
    # Check if line should be removed
    for pattern in REMOVE_PATTERNS:
        if re.search(pattern, line, re.IGNORECASE):
            # If the line is only a comment, remove it entirely
            if re.match(r'^\s*#', line):
                return None  # Signal to remove line
            # If comment is at end of line, remove just the comment
            line = re.sub(pattern, '', line, flags=re.IGNORECASE)
    
    return line

def sanitize_file(filepath: Path) -> tuple[int, int]:
    """
    Sanitize a single Python file.
    Returns (lines_removed, lines_modified).
    """
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            lines = f.readlines()
    except Exception as e:
        print(f"Error reading {filepath}: {e}")
        return 0, 0
    
    new_lines = []
    lines_removed = 0
    lines_modified = 0
    
    for line in lines:
        sanitized = sanitize_line(line)
        if sanitized is None:
            lines_removed += 1
        elif sanitized != line:
            new_lines.append(sanitized)
            lines_modified += 1
        else:
            new_lines.append(line)
    
    # Only write if changes were made
    if lines_removed > 0 or lines_modified > 0:
        try:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.writelines(new_lines)
        except Exception as e:
            print(f"Error writing {filepath}: {e}")
            return 0, 0
    
    return lines_removed, lines_modified

def sanitize_directory(directory: Path, exclude_dirs: set = None) -> dict:
    """
    Sanitize all Python files in directory recursively.
    Returns statistics.
    """
    if exclude_dirs is None:
        exclude_dirs = {'.venv', 'venv', '__pycache__', '.pytest_cache', 
                       'node_modules', '.git', 'dist', 'build'}
    
    stats = {
        'files_processed': 0,
        'files_modified': 0,
        'lines_removed': 0,
        'lines_modified': 0,
    }
    
    for root, dirs, files in os.walk(directory):
        # Remove excluded directories from search
        dirs[:] = [d for d in dirs if d not in exclude_dirs]
        
        for file in files:
            if file.endswith('.py'):
                filepath = Path(root) / file
                removed, modified = sanitize_file(filepath)
                
                stats['files_processed'] += 1
                if removed > 0 or modified > 0:
                    stats['files_modified'] += 1
                    stats['lines_removed'] += removed
                    stats['lines_modified'] += modified
                    print(f"✓ {filepath.relative_to(directory)}: "
                          f"{removed} removed, {modified} modified")
    
    return stats

if __name__ == '__main__':
    # Sanitize backend
    print("=" * 60)
    print("Sanitizing backend Python files...")
    print("=" * 60)
    backend_stats = sanitize_directory(Path('backend'))
    
    print("\n" + "=" * 60)
    print("Backend Sanitization Complete")
    print("=" * 60)
    print(f"Files processed: {backend_stats['files_processed']}")
    print(f"Files modified: {backend_stats['files_modified']}")
    print(f"Lines removed: {backend_stats['lines_removed']}")
    print(f"Lines modified: {backend_stats['lines_modified']}")
    
    # Sanitize root level scripts
    print("\n" + "=" * 60)
    print("Sanitizing root Python files...")
    print("=" * 60)
    root_stats = sanitize_directory(Path('.'), exclude_dirs={
        '.venv', 'venv', '__pycache__', '.pytest_cache', 'node_modules', 
        '.git', 'dist', 'build', 'backend', 'frontend', 'frontend_legacy',
        'data', 'models', 'storage', '.kiro', '.github', '.idea', '.ruff_cache'
    })
    
    print("\n" + "=" * 60)
    print("Root Sanitization Complete")
    print("=" * 60)
    print(f"Files processed: {root_stats['files_processed']}")
    print(f"Files modified: {root_stats['files_modified']}")
    print(f"Lines removed: {root_stats['lines_removed']}")
    print(f"Lines modified: {root_stats['lines_modified']}")
    
    print("\n" + "=" * 60)
    print("TOTAL SANITIZATION COMPLETE")
    print("=" * 60)
    total_files = backend_stats['files_processed'] + root_stats['files_processed']
    total_modified = backend_stats['files_modified'] + root_stats['files_modified']
    total_removed = backend_stats['lines_removed'] + root_stats['lines_removed']
    total_changed = backend_stats['lines_modified'] + root_stats['lines_modified']
    print(f"Total files processed: {total_files}")
    print(f"Total files modified: {total_modified}")
    print(f"Total lines removed: {total_removed}")
    print(f"Total lines modified: {total_changed}")
