#!/usr/bin/env python3
"""Generate bash completion script for Pharos CLI."""

import sys


def get_bash_completion_script() -> str:
    """Generate the bash completion script."""
    return '''# bash completion for pharos CLI
# Generated by Pharos CLI

_pharos_completions() {
    local cur prev words cword
    _init_completion || return

    # Main commands
    local commands="auth config resource collection search graph batch chat recommend annotate quality taxonomy code ask system backup version completion info"

    # Resource subcommands
    local resource_cmds="add list get update delete import export"

    # Collection subcommands
    local collection_cmds="create list show add remove delete export"

    # Search options
    local search_opts="--semantic --hybrid --weight --type --language --min-quality --format --page --per-page --output --help"

    # Auth subcommands
    local auth_cmds="login logout whoami"

    # Graph subcommands
    local graph_cmds="stats citations related export contradictions discover centrality"

    # Annotation subcommands
    local annotate_cmds="list search delete export import"

    # Quality subcommands
    local quality_cmds="score outliers recompute report"

    # Taxonomy subcommands
    local taxonomy_cmds="list classify train stats"

    # Recommend subcommands
    local recommend_cmds="for-user similar explain"

    # Code subcommands
    local code_cmds="analyze ast deps chunk scan"

    # System subcommands
    local system_cmds="health stats version"

    # Backup subcommands
    local backup_cmds="backup restore"

    # Batch subcommands
    local batch_cmds="delete update export"

    # Handle first argument (main command)
    if [[ $cword -eq 1 ]]; then
        COMPREPLY=($(compgen -W "$commands" -- "$cur"))
        return
    fi

    # Handle subcommands
    local cmd="${words[1]}"
    local subcmd="${words[2]}"

    case "$cmd" in
        auth)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "$auth_cmds" -- "$cur"))
            fi
            ;;
        resource)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "$resource_cmds" -- "$cur"))
            elif [[ "$subcmd" == "add" ]]; then
                _filedir
            elif [[ "$subcmd" == "get" || "$subcmd" == "update" || "$subcmd" == "delete" || "$subcmd" == "export" ]]; then
                COMPREPLY=($(compgen -W "$(pharos resource list --quiet 2>/dev/null | tr ',' ' ')" -- "$cur"))
            fi
            ;;
        collection)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "$collection_cmds" -- "$cur"))
            elif [[ "$subcmd" == "show" || "$subcmd" == "delete" || "$subcmd" == "export" ]]; then
                COMPREPLY=($(compgen -W "$(pharos collection list --quiet 2>/dev/null | tr ',' ' ')" -- "$cur"))
            elif [[ "$subcmd" == "add" || "$subcmd" == "remove" ]]; then
                COMPREPLY=($(compgen -W "$(pharos collection list --quiet 2>/dev/null | tr ',' ' ')" -- "$cur"))
            fi
            ;;
        search)
            COMPREPLY=($(compgen -W "$search_opts" -- "$cur"))
            ;;
        graph)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "$graph_cmds" -- "$cur"))
            elif [[ "$subcmd" == "citations" || "$subcmd" == "related" ]]; then
                COMPREPLY=($(compgen -W "$(pharos resource list --quiet 2>/dev/null | tr ',' ' ')" -- "$cur"))
            fi
            ;;
        annotate)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "$annotate_cmds" -- "$cur"))
            elif [[ "$subcmd" == "list" || "$subcmd" == "search" || "$subcmd" == "export" ]]; then
                COMPREPLY=($(compgen -W "$(pharos resource list --quiet 2>/dev/null | tr ',' ' ')" -- "$cur"))
            fi
            ;;
        quality)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "$quality_cmds" -- "$cur"))
            elif [[ "$subcmd" == "score" || "$subcmd" == "recompute" ]]; then
                COMPREPLY=($(compgen -W "$(pharos resource list --quiet 2>/dev/null | tr ',' ' ')" -- "$cur"))
            elif [[ "$subcmd" == "report" ]]; then
                COMPREPLY=($(compgen -W "$(pharos collection list --quiet 2>/dev/null | tr ',' ' ')" -- "$cur"))
            fi
            ;;
        taxonomy)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "$taxonomy_cmds" -- "$cur"))
            elif [[ "$subcmd" == "classify" ]]; then
                COMPREPLY=($(compgen -W "$(pharos resource list --quiet 2>/dev/null | tr ',' ' ')" -- "$cur"))
            fi
            ;;
        recommend)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "$recommend_cmds" -- "$cur"))
            elif [[ "$subcmd" == "similar" || "$subcmd" == "explain" ]]; then
                COMPREPLY=($(compgen -W "$(pharos resource list --quiet 2>/dev/null | tr ',' ' ')" -- "$cur"))
            fi
            ;;
        code)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "$code_cmds" -- "$cur"))
            elif [[ "$subcmd" == "analyze" || "$subcmd" == "ast" || "$subcmd" == "deps" || "$subcmd" == "chunk" ]]; then
                _filedir
            elif [[ "$subcmd" == "scan" ]]; then
                _filedir -d
            fi
            ;;
        system)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "$system_cmds" -- "$cur"))
            fi
            ;;
        backup)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "$backup_cmds" -- "$cur"))
            elif [[ "$subcmd" == "restore" ]]; then
                _filedir
            fi
            ;;
        batch)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "$batch_cmds" -- "$cur"))
            fi
            ;;
        completion)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "bash zsh fish" -- "$cur"))
            fi
            ;;
    esac
}

complete -F _pharos_completions pharos
'''


def main():
    """Main entry point."""
    print(get_bash_completion_script())


if __name__ == "__main__":
    main()