#!/usr/bin/env python3
"""Generate fish completion script for Pharos CLI."""

import sys


def get_fish_completion_script() -> str:
    """Generate the fish completion script."""
    return '''# fish completion for pharos CLI
# Generated by Pharos CLI

# Main command
complete -c pharos -f -a 'auth config resource collection search graph batch chat recommend annotate quality taxonomy code ask system backup version completion info'

# Global options
complete -c pharos -f -l color -a 'auto always never' -d 'Color output'
complete -c pharos -f -l no-color -d 'Disable color output'
complete -c pharos -f -l help -d 'Show help'
complete -c pharos -f -s h -l version -d 'Show version'

# Auth command
complete -c pharos -f -a 'login logout whoami' -d 'Authentication commands'
complete -c pharos -f -a 'login' -d 'Login to Pharos'
complete -c pharos -f -a 'logout' -d 'Logout from Pharos'
complete -c pharos -f -a 'whoami' -d 'Show current user'

# Config command
complete -c pharos -f -a 'show set' -d 'Configuration commands'
complete -c pharos -f -a 'show' -d 'Show current configuration'
complete -c pharos -f -a 'set' -d 'Set configuration value'

# Resource command
complete -c pharos -f -a 'add list get update delete import export' -d 'Resource management commands'
complete -c pharos -f -a 'add' -d 'Add a new resource'
complete -c pharos -f -a 'list' -d 'List resources'
complete -c pharos -f -a 'get' -d 'Get resource details'
complete -c pharos -f -a 'update' -d 'Update resource metadata'
complete -c pharos -f -a 'delete' -d 'Delete a resource'
complete -c pharos -f -a 'import' -d 'Import resources from directory'
complete -c pharos -f -a 'export' -d 'Export resource content'

# Resource add options
complete -c pharos -f -a 'add' -l title -d 'Resource title'
complete -c pharos -f -a 'add' -l type -d 'Resource type' -a 'code paper documentation url'
complete -c pharos -f -a 'add' -l language -d 'Programming language'
complete -c pharos -f -a 'add' -l url -d 'Add from URL'
complete -c pharos -f -a 'add' -l stdin -d 'Add from stdin'

# Resource list options
complete -c pharos -f -a 'list' -l type -d 'Filter by type' -a 'code paper documentation'
complete -c pharos -f -a 'list' -l language -d 'Filter by language'
complete -c pharos -f -a 'list' -l min-quality -d 'Minimum quality score'
complete -c pharos -f -a 'list' -l format -d 'Output format' -a 'table json csv tree'
complete -c pharos -f -a 'list' -l page -d 'Page number'
complete -c pharos -f -a 'list' -l per-page -d 'Items per page'

# Collection command
complete -c pharos -f -a 'create list show add remove delete export' -d 'Collection management commands'
complete -c pharos -f -a 'create' -d 'Create a new collection'
complete -c pharos -f -a 'list' -d 'List collections'
complete -c pharos -f -a 'show' -d 'Show collection contents'
complete -c pharos -f -a 'add' -d 'Add resource to collection'
complete -c pharos -f -a 'remove' -d 'Remove resource from collection'
complete -c pharos -f -a 'delete' -d 'Delete a collection'
complete -c pharos -f -a 'export' -d 'Export collection'

# Search command
complete -c pharos -f -a 'search' -d 'Search for resources'
complete -c pharos -f -a 'search' -l semantic -d 'Use semantic search'
complete -c pharos -f -a 'search' -l hybrid -d 'Use hybrid search'
complete -c pharos -f -a 'search' -l weight -d 'Hybrid search weight' -a '0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9'
complete -c pharos -f -a 'search' -l type -d 'Filter by type' -a 'code paper documentation'
complete -c pharos -f -a 'search' -l language -d 'Filter by language'
complete -c pharos -f -a 'search' -l min-quality -d 'Minimum quality score'
complete -c pharos -f -a 'search' -l format -d 'Output format' -a 'table json csv tree'
complete -c pharos -f -a 'search' -l page -d 'Page number'
complete -c pharos -f -a 'search' -l per-page -d 'Items per page'
complete -c pharos -f -a 'search' -l output -d 'Save results to file' -r

# Graph command
complete -c pharos -f -a 'stats citations related export contradictions discover centrality' -d 'Knowledge graph and citation commands'
complete -c pharos -f -a 'stats' -d 'Show graph statistics'
complete -c pharos -f -a 'citations' -d 'Find citations for resource'
complete -c pharos -f -a 'related' -d 'Find related resources'
complete -c pharos -f -a 'export' -d 'Export graph data'
complete -c pharos -f -a 'contradictions' -d 'Detect contradictions'
complete -c pharos -f -a 'discover' -d 'Find hidden connections'
complete -c pharos -f -a 'centrality' -d 'Show centrality scores'

# Graph options
complete -c pharos -f -a 'citations' -l limit -d 'Maximum results'
complete -c pharos -f -a 'related' -l limit -d 'Maximum results'
complete -c pharos -f -a 'centrality' -l top -d 'Show top N nodes'
complete -c pharos -f -a 'export' -l format -d 'Export format' -a 'graphml json csv'

# Batch command
complete -c pharos -f -a 'delete update export' -d 'Batch operations for resources and collections'
complete -c pharos -f -a 'delete' -d 'Batch delete resources'
complete -c pharos -f -a 'update' -d 'Batch update metadata'
complete -c pharos -f -a 'export' -d 'Batch export'

# Batch options
complete -c pharos -f -a 'delete' -l ids -d 'Resource IDs (comma-separated)'
complete -c pharos -f -a 'update' -l file -d 'Update file (JSON)' -r
complete -c pharos -f -a 'export' -l collection -d 'Collection ID'
complete -c pharos -f -a 'export' -l output -d 'Output directory' -r
complete -c pharos -f -a 'batch' -l dry-run -d 'Dry run (no changes)'

# Chat command
complete -c pharos -f -a 'chat' -d 'Interactive chat with your knowledge base'

# Recommend command
complete -c pharos -f -a 'for-user similar explain' -d 'Get recommendations for resources'
complete -c pharos -f -a 'for-user' -d 'Get recommendations for user'
complete -c pharos -f -a 'similar' -d 'Get similar resources'
complete -c pharos -f -a 'explain' -d 'Explain recommendation'

# Recommend options
complete -c pharos -f -a 'for-user' -l user -d 'User ID'
complete -c pharos -f -a 'for-user' -l limit -d 'Maximum results' -a '5 10 20 50'
complete -c pharos -f -a 'similar' -l limit -d 'Maximum results' -a '5 10 20 50'
complete -c pharos -f -a 'explain' -l for-user -d 'User ID'

# Annotate command
complete -c pharos -f -a 'list search delete export import' -d 'Annotation management commands'
complete -c pharos -f -a 'list' -d 'List annotations for resource'
complete -c pharos -f -a 'search' -d 'Search annotations'
complete -c pharos -f -a 'delete' -d 'Delete annotation'
complete -c pharos -f -a 'export' -d 'Export annotations'
complete -c pharos -f -a 'import' -d 'Import annotations'

# Annotate options
complete -c pharos -f -a 'annotate' -l text -d 'Annotation text'
complete -c pharos -f -a 'annotate' -l start -d 'Start position'
complete -c pharos -f -a 'annotate' -l end -d 'End position'
complete -c pharos -f -a 'annotate' -l type -d 'Annotation type' -a 'highlight note tag'
complete -c pharos -f -a 'export' -l format -d 'Export format' -a 'md json csv'

# Quality command
complete -c pharos -f -a 'score outliers recompute report' -d 'Quality assessment commands'
complete -c pharos -f -a 'score' -d 'Get quality score'
complete -c pharos -f -a 'outliers' -d 'List quality outliers'
complete -c pharos -f -a 'recompute' -d 'Recompute quality scores'
complete -c pharos -f -a 'report' -d 'Quality report for collection'

# Quality options
complete -c pharos -f -a 'outliers' -l threshold -d 'Outlier threshold'
complete -c pharos -f -a 'outliers' -l format -d 'Output format' -a 'table json'

# Taxonomy command
complete -c pharos -f -a 'list classify train stats' -d 'Taxonomy and classification commands'
complete -c pharos -f -a 'list' -d 'List taxonomy nodes'
complete -c pharos -f -a 'classify' -d 'Classify resource'
complete -c pharos -f -a 'train' -d 'Train classifier'
complete -c pharos -f -a 'stats' -d 'Show classification distribution'

# Code command
complete -c pharos -f -a 'analyze ast deps chunk scan' -d 'Code analysis and intelligence commands'
complete -c pharos -f -a 'analyze' -d 'Analyze code file'
complete -c pharos -f -a 'ast' -d 'Extract AST'
complete -c pharos -f -a 'deps' -d 'Find dependencies'
complete -c pharos -f -a 'chunk' -d 'Chunk code file'
complete -c pharos -f -a 'scan' -d 'Scan repository'

# Code options
complete -c pharos -f -a 'chunk' -l strategy -d 'Chunking strategy' -a 'ast lines sentences'
complete -c pharos -f -a 'scan' -l recursive -d 'Scan recursively'
complete -c pharos -f -a 'scan' -l language -d 'Language filter'

# Ask command
complete -c pharos -f -a 'ask' -d 'Ask questions and get answers from your knowledge base'
complete -c pharos -f -a 'ask' -l show-sources -d 'Show evidence sources'
complete -c pharos -f -a 'ask' -l strategy -d 'Retrieval strategy' -a 'graphrag hybrid vector'

# System command
complete -c pharos -f -a 'health stats version' -d 'System management commands'
complete -c pharos -f -a 'health' -d 'Health check'
complete -c pharos -f -a 'stats' -d 'System statistics'
complete -c pharos -f -a 'version' -d 'Show version'

# Backup command
complete -c pharos -f -a 'backup restore' -d 'Backup and restore commands'
complete -c pharos -f -a 'backup' -d 'Create backup'
complete -c pharos -f -a 'restore' -d 'Restore from backup'

# Backup options
complete -c pharos -f -a 'backup' -l output -d 'Output file' -r
complete -c pharos -f -a 'restore' -l verify -d 'Verify backup before restore'

# Completion command
complete -c pharos -f -a 'completion' -d 'Generate shell completion script'
complete -c pharos -f -a 'completion' -a 'bash zsh fish' -d 'Shell type'

# Version command
complete -c pharos -f -a 'version' -d 'Show version information'

# Info command
complete -c pharos -f -a 'info' -d 'Show terminal and color information'
'''


def main():
    """Main entry point."""
    print(get_fish_completion_script())


if __name__ == "__main__":
    main()