#!/usr/bin/env python3
"""Generate zsh completion script for Pharos CLI."""

import sys


def get_zsh_completion_script() -> str:
    """Generate the zsh completion script."""
    return '''# zsh completion for pharos CLI
# Generated by Pharos CLI

autoload -U compinit
compinit

# Main commands
local -a pharos_commands
pharos_commands=(
    "auth:Authentication commands"
    "config:Configuration commands"
    "resource:Resource management commands"
    "collection:Collection management commands"
    "search:Search for resources"
    "graph:Knowledge graph and citation commands"
    "batch:Batch operations for resources and collections"
    "chat:Interactive chat with your knowledge base"
    "recommend:Get recommendations for resources"
    "annotate:Annotation management commands"
    "quality:Quality assessment commands"
    "taxonomy:Taxonomy and classification commands"
    "code:Code analysis and intelligence commands"
    "ask:Ask questions and get answers from your knowledge base"
    "system:System management commands"
    "backup:Backup and restore commands"
    "version:Show version information"
    "completion:Generate shell completion script"
    "info:Show terminal and color information"
)

# Auth subcommands
local -a pharos_auth_commands
pharos_auth_commands=(
    "login:Login to Pharos"
    "logout:Logout from Pharos"
    "whoami:Show current user"
)

# Resource subcommands
local -a pharos_resource_commands
pharos_resource_commands=(
    "add:Add a new resource"
    "list:List resources"
    "get:Get resource details"
    "update:Update resource metadata"
    "delete:Delete a resource"
    "import:Import resources from directory"
    "export:Export resource content"
)

# Collection subcommands
local -a pharos_collection_commands
pharos_collection_commands=(
    "create:Create a new collection"
    "list:List collections"
    "show:Show collection contents"
    "add:Add resource to collection"
    "remove:Remove resource from collection"
    "delete:Delete a collection"
    "export:Export collection"
)

# Graph subcommands
local -a pharos_graph_commands
pharos_graph_commands=(
    "stats:Show graph statistics"
    "citations:Find citations for resource"
    "related:Find related resources"
    "export:Export graph data"
    "contradictions:Detect contradictions"
    "discover:Find hidden connections"
    "centrality:Show centrality scores"
)

# Annotation subcommands
local -a pharos_annotate_commands
pharos_annotate_commands=(
    "list:List annotations for resource"
    "search:Search annotations"
    "delete:Delete annotation"
    "export:Export annotations"
    "import:Import annotations"
)

# Quality subcommands
local -a pharos_quality_commands
pharos_quality_commands=(
    "score:Get quality score"
    "outliers:List quality outliers"
    "recompute:Recompute quality scores"
    "report:Quality report for collection"
)

# Taxonomy subcommands
local -a pharos_taxonomy_commands
pharos_taxonomy_commands=(
    "list:List taxonomy nodes"
    "classify:Classify resource"
    "train:Train classifier"
    "stats:Show classification distribution"
)

# Recommend subcommands
local -a pharos_recommend_commands
pharos_recommend_commands=(
    "for-user:Get recommendations for user"
    "similar:Get similar resources"
    "explain:Explain recommendation"
)

# Code subcommands
local -a pharos_code_commands
pharos_code_commands=(
    "analyze:Analyze code file"
    "ast:Extract AST"
    "deps:Find dependencies"
    "chunk:Chunk code file"
    "scan:Scan repository"
)

# System subcommands
local -a pharos_system_commands
pharos_system_commands=(
    "health:Health check"
    "stats:System statistics"
    "version:Show version"
)

# Backup subcommands
local -a pharos_backup_commands
pharos_backup_commands=(
    "backup:Create backup"
    "restore:Restore from backup"
)

# Batch subcommands
local -a pharos_batch_commands
pharos_batch_commands=(
    "delete:Batch delete resources"
    "update:Batch update metadata"
    "export:Batch export"
)

# Search options
local -a pharos_search_options
pharos_search_options=(
    "--semantic:Use semantic search"
    "--hybrid:Use hybrid search"
    "--weight:Hybrid search weight"
    "--type:Filter by resource type"
    "--language:Filter by language"
    "--min-quality:Minimum quality score"
    "--format:Output format"
    "--page:Page number"
    "--per-page:Items per page"
    "--output:Save results to file"
    "--help:Show help"
)

# Global options
local -a pharos_global_options
pharos_global_options=(
    "--color:Color output (auto, always, never)"
    "--no-color:Disable color output"
    "--help:Show help"
    "--version:Show version"
)

# Helper function to get resource IDs
_pharos_resource_ids() {
    local ids
    ids=$(pharos resource list --quiet 2>/dev/null | tr ',' ' ')
    _describe -t resource-ids 'resource ID' $ids
}

# Helper function to get collection IDs
_pharos_collection_ids() {
    local ids
    ids=$(pharos collection list --quiet 2>/dev/null | tr ',' ' ')
    _describe -t collection-ids 'collection ID' $ids
}

# Helper function for file arguments
_pharos_files() {
    _files
}

# Helper function for directory arguments
_pharos_directories() {
    _directories
}

# Main pharos command
_pharos() {
    local -a context state line
    _arguments -C \
        '(- :)'{-v,--version}'[Show version]' \
        '(- :)'{-h,--help}'[Show help]' \
        '--color[Color output]:color mode:(auto always never)' \
        '--no-color[Disable color output]' \
        '1: :_pharos_commands' \
        '*::arg:->args'

    case $state in
        args)
            local cmd="${words[1]}"
            case $cmd in
                auth)
                    _arguments -C \
                        '1: :_pharos_auth_commands' \
                        '*::arg:->args'
                    ;;
                resource)
                    _arguments -C \
                        '1: :_pharos_resource_commands' \
                        '*::arg:->args'
                    ;;
                collection)
                    _arguments -C \
                        '1: :_pharos_collection_commands' \
                        '*::arg:->args'
                    ;;
                search)
                    _arguments -C \
                        '1:query' \
                        $pharos_search_options \
                        $pharos_global_options
                    ;;
                graph)
                    _arguments -C \
                        '1: :_pharos_graph_commands' \
                        '*::arg:->args'
                    ;;
                annotate)
                    _arguments -C \
                        '1: :_pharos_annotate_commands' \
                        '*::arg:->args'
                    ;;
                quality)
                    _arguments -C \
                        '1: :_pharos_quality_commands' \
                        '*::arg:->args'
                    ;;
                taxonomy)
                    _arguments -C \
                        '1: :_pharos_taxonomy_commands' \
                        '*::arg:->args'
                    ;;
                recommend)
                    _arguments -C \
                        '1: :_pharos_recommend_commands' \
                        '*::arg:->args'
                    ;;
                code)
                    _arguments -C \
                        '1: :_pharos_code_commands' \
                        '*::arg:->args'
                    ;;
                system)
                    _arguments -C \
                        '1: :_pharos_system_commands' \
                        '*::arg:->args'
                    ;;
                backup)
                    _arguments -C \
                        '1: :_pharos_backup_commands' \
                        '*::arg:->args'
                    ;;
                batch)
                    _arguments -C \
                        '1: :_pharos_batch_commands' \
                        '*::arg:->args'
                    ;;
                completion)
                    _arguments -C \
                        '1:shell:(bash zsh fish)' \
                        $pharos_global_options
                    ;;
                config|chat|version|info)
                    _arguments $pharos_global_options
                    ;;
            esac
            ;;
    esac
}

# Command completion
_pharos_commands() {
    _describe -t commands 'pharos command' pharos_commands
}

# Auth subcommand completion
_pharos_auth_commands() {
    _describe -t auth-commands 'auth command' pharos_auth_commands
}

# Resource subcommand completion
_pharos_resource_commands() {
    _describe -t resource-commands 'resource command' pharos_resource_commands
}

# Collection subcommand completion
_pharos_collection_commands() {
    _describe -t collection-commands 'collection command' pharos_collection_commands
}

# Graph subcommand completion
_pharos_graph_commands() {
    _describe -t graph-commands 'graph command' pharos_graph_commands
}

# Annotate subcommand completion
_pharos_annotate_commands() {
    _describe -t annotate-commands 'annotate command' pharos_annotate_commands
}

# Quality subcommand completion
_pharos_quality_commands() {
    _describe -t quality-commands 'quality command' pharos_quality_commands
}

# Taxonomy subcommand completion
_pharos_taxonomy_commands() {
    _describe -t taxonomy-commands 'taxonomy command' pharos_taxonomy_commands
}

# Recommend subcommand completion
_pharos_recommend_commands() {
    _describe -t recommend-commands 'recommend command' pharos_recommend_commands
}

# Code subcommand completion
_pharos_code_commands() {
    _describe -t code-commands 'code command' pharos_code_commands
}

# System subcommand completion
_pharos_system_commands() {
    _describe -t system-commands 'system command' pharos_system_commands
}

# Backup subcommand completion
_pharos_backup_commands() {
    _describe -t backup-commands 'backup command' pharos_backup_commands
}

# Batch subcommand completion
_pharos_batch_commands() {
    _describe -t batch-commands 'batch command' pharos_batch_commands
}

# Register the completion function
compdef _pharos pharos
'''


def main():
    """Main entry point."""
    print(get_zsh_completion_script())


if __name__ == "__main__":
    main()