"""Utils module for Pharos CLI."""

from pharos_cli.utils.console import get_console, console
from pharos_cli.utils.progress import (
    get_progress,
    get_file_progress,
    get_batch_progress,
    Spinner,
    progress_context,
    iter_with_progress,
    iter_with_callback,
    iter_with_status,
    spinner_context,
    track_progress,
    ProgressStats,
    ThroughputColumn,
)
from pharos_cli.utils.validators import validate_url, validate_file_path
from pharos_cli.utils.helpers import format_number, format_duration, truncate
from pharos_cli.utils.pager import (
    PagerMode,
    PagerNotAvailableError,
    get_pager_executable,
    is_pager_available,
    should_use_pager,
    get_pager_mode_from_string,
    pager_context,
    display_through_pager,
    PagerManager,
    get_pager_manager,
    reset_pager_manager,
)

__all__ = [
    "get_console",
    "console",
    "get_progress",
    "get_file_progress",
    "get_batch_progress",
    "Spinner",
    "progress_context",
    "iter_with_progress",
    "iter_with_callback",
    "iter_with_status",
    "spinner_context",
    "track_progress",
    "ProgressStats",
    "ThroughputColumn",
    "validate_url",
    "validate_file_path",
    "format_number",
    "format_duration",
    "truncate",
    "PagerMode",
    "PagerNotAvailableError",
    "get_pager_executable",
    "is_pager_available",
    "should_use_pager",
    "get_pager_mode_from_string",
    "pager_context",
    "display_through_pager",
    "PagerManager",
    "get_pager_manager",
    "reset_pager_manager",
]